name: Deploy React App
on: push
jobs:
    # Можно разбивать на несколько Jobs
    # У всех должна быть часть от задания имени до npm ci
    delpoy:
        runs-on: ubuntu-latest
        steps:
            - name: Get repository code
              uses: actions/checkout@v3
            - name: Install deps
              run: npm ci
            - name: Test app
              run: npm run test
            - name: Lint app
              run: npm run lint
            - name: Build app
              run: npm run build
            - name: Deploy
              run: echo  Deploying..
